# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20190227_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quote',
            new_name='Quotes',
        ),
    ]
